export enum EventName {
    Touch_Start = "Touch_Start",
    Touch_Move = "Touch_Move",
    Touch_End = "Touch_End",
    LevelEvent = "LevelEvent",
    level2Event = "level2Event",
    HitEnemy = "HitEnemy",
    Scale_Range_Change = "Scale_Range_Change",
    Dodge_Add_AtkCD = "Dodge_Add_AtkCD",
    Enemy_Die = "Enemy_Die",
    PlayerMoveType = "PlayerMoveType",
    diamondEvent = "diamondEvent",
    coinEvent = "coinEvent",
    GameOver = "GameOver",
    Status = "Status",
    IntroFinish = "IntroFinish",
    SelectRole = "SelectRole",
    NextWave = "NextWave",
    ClearEnemy = "ClearEnemy"
}
